### ISSUE TITLE
Duplicate `fetchData` call when not using server side rendering

### ISSUE THREAD

**Issue by bmac** [digiaonline/redux-fetch-data#2]
### What did you do?

Hello, I'm currently using `redux-fetch-data` without server side rendering. Due to an IT policy that I have no influence over I'm unable to deploy a node server for my app. However, I am taking advantage of this library and `fetchDataOnServer` to create a test helper method for writing acceptance tests where I wait until all the data is loaded for my route before I make assertions about the state of my dom.

I have a client setup similar to the example from the readme. But critically I am not setting the initialState of my store and `state.fetching.fetched` is `false` when the app initially loads.

``` js
import React from 'react';
import { createStore, combineReducers } from 'redux';
import { render } from 'react-dom';
import { Router, browserHistory } from 'react-router';
import { Provider } from 'react-redux';
import { FetchData, reducer as fetching } from 'redux-fetch-data';

import routes from './routes';

// No initial state setting { fetching: { fetched: true } } here
const store = createStore(combineReducers({ fetching }));

render(
  <Provider store={store} key="provider">
    <Router render={props => <FetchData {...props}/>}
            history={browserHistory}
            routes={routes}/>
  </Provider>,
  document.getElementById('root')
);
```
### What did you expect to happen?

I expected the `fetchData` static method on my route to be called once when the app was loaded.
### What actually happened?

The `fetchData` static method on my route to be called twice when the app was loaded.

The first time it was called from the `FetchData` component's [componentWillMount](https://github.com/nordsoftware/redux-fetch-data/blob/develop/src/fetch-data.js#L10) function.

However, once this fetch succeeds `state.fetching.fetched` is updated to `true` and the [mapStateToProps](https://github.com/nordsoftware/redux-fetch-data/blob/develop/src/fetch-data.js#L49-L53) function triggers  the `FetchData` component's [componentWillReceiveProps](https://github.com/nordsoftware/redux-fetch-data/blob/develop/src/fetch-data.js#L15-L17) method to be invoked triggering a second `fetchData`.

After the first route is loaded subsequent route changes only trigger one `fetchData` as expected.

As a workaround, I have removed the `reducer` provided by `redux-fetch-data` and I set the initialState for the store to `state.fetching.fetched = false` to prevent the `componentWillReceiveProps` from being triggered when `state.fetching.fetched` changes.  This fixes my issue, however, I'm not crazy about this workaround because of the coupling the state structure of `redux-fetch-data`'s reducer.
### What version of this module are you using?

I am using version `0.1.3` from npm.

**Comment by hugovk** [comment]
Thanks for the report, however we are going to archive this repo because we're no longer using or maintaining it.
